# @format

name: deploy to EC2

on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy to EC2
        uses: appleboy/ssh-action@master
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        with:
          host: ${{ secrets.EC2HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          envs: GROQ_API_KEY
          script: |
            sudo docker pull dhruvamaheshwari47/nayasur_app:latest
            sudo docker rm -f nayasur || true
            sudo docker run -d -p 4000:4000 -e GROQ_API_KEY=$GROQ_API_KEY --name nayasur dhruvamaheshwari47/nayasur_app:latest
